name: Deploy RabbitMQ to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            mkdir -p ~/cerca-queue
            cd ~/cerca-queue

            if [ -d ".git" ]; then
              git pull
            else
              git clone https://github.com/${{ github.repository }}.git .
            fi

            echo "RABBIT_USER=${{ secrets.RABBIT_USER }}" > .env
            echo "RABBIT_PASSWORD=${{ secrets.RABBIT_PASSWORD }}" >> .env

            docker compose down
            docker compose up -d

            cd ~
            rm -rf $TEMP_DIR
